#!/usr/bin/env python3
"""Triage MSP430/MSP430X disassembly for Smart Battery command call sites.

Consumes the text listing generated by disassemble_battery_msp430x.py. This is
heuristic: it flags nearby command literals and call/calla instructions so a
human can identify the common SMBus primitive before assigning function names.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

COMMANDS = {
    0x08:"Temperature",0x09:"Voltage",0x0A:"Current",0x0B:"AverageCurrent",
    0x0C:"MaxError",0x0D:"RelativeSOC",0x0E:"AbsoluteSOC",
    0x0F:"RemainingCapacity",0x10:"FullChargeCapacity",0x14:"ChargingCurrent",
    0x15:"ChargingVoltage",0x16:"BatteryStatus",0x17:"CycleCount",
    0x18:"DesignCapacity",0x19:"DesignVoltage",0x1B:"ManufactureDate",
    0x1C:"SerialNumber",0x23:"ManufacturerData",
}
CALL_RE = re.compile(r"\b(call|calla)\b", re.I)
IMM_RE = re.compile(r"#0x([0-9a-fA-F]+)|#([0-9]+)\b")


def literal(line: str):
    for m in IMM_RE.finditer(line):
        value = int(m.group(1),16) if m.group(1) else int(m.group(2))
        if value in COMMANDS:
            return value
    return None


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("listing",type=Path)
    ap.add_argument("--window",type=int,default=8)
    args=ap.parse_args()
    lines=args.listing.read_text(errors="replace").splitlines()

    hits=[]
    for i,line in enumerate(lines):
        cmd=literal(line)
        if cmd is None: continue
        lo=max(0,i-args.window); hi=min(len(lines),i+args.window+1)
        calls=[(j,lines[j]) for j in range(lo,hi) if CALL_RE.search(lines[j])]
        if calls: hits.append((i,cmd,calls))

    print(f"candidate_command_call_sites={len(hits)}")
    for i,cmd,calls in hits:
        print(f"\n== {COMMANDS[cmd]} (0x{cmd:02X}) near line {i+1} ==")
        for j in range(max(0,i-3),min(len(lines),i+4)):
            print(("> " if j==i else "  ")+lines[j])
        for j,line in calls:
            print(f"  nearby-call line {j+1}: {line}")

if __name__=="__main__": main()
